import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';

import { createShadowStyle } from './shadowStyles';

const WORK_DARK = '#0a2f7b';
const WORK_LIGHT = '#eef4ff';
const WORK_MID = '#123c9c';
const WORK_ACCENT = '#5b7edc';
const WORK_ACCENT_SOFT = '#c7d6ff';

type NamedStyles = Record<string, ViewStyle | TextStyle | ImageStyle>;

export const layoutStyles = {
  container: {
    flex: 1,
    backgroundColor: '#f4f4f5',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: 24,
  },
  panel: {
    padding: 24,
    borderRadius: 24,
    backgroundColor: '#ffffff',
    ...createShadowStyle({ color: '#111827', opacity: 0.08, offsetX: 0, offsetY: 16, radius: 32 }),
    elevation: 6,
    gap: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  subtitle: {
    fontSize: 14,
    color: '#6b7280',
  },
  syncHint: {
    fontSize: 12,
    color: '#9ca3af',
  },
  reminderStack: {
    gap: 8,
    marginBottom: 12,
  },
  reminderCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
  },
  reminderCardWarning: {
    backgroundColor: '#fef2f2',
    borderColor: '#fca5a5',
  },
  reminderCardInfo: {
    backgroundColor: '#ecfeff',
    borderColor: '#67e8f9',
  },
  reminderText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#0f172a',
  },
  reminderTextWarning: {
    color: '#b91c1c',
  },
  reminderTextInfo: {
    color: '#0f172a',
  },
  reminderActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reminderActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#0f172a',
    backgroundColor: '#ffffff',
  },
  reminderActionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0f172a',
  },
  toastContainer: {
    borderRadius: 16,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  toastInfo: {
    backgroundColor: '#ecfeff',
    borderColor: '#67e8f9',
  },
  toastWarning: {
    backgroundColor: '#fef2f2',
    borderColor: '#fca5a5',
  },
  toastDanger: {
    backgroundColor: '#fef2f2',
    borderColor: '#f87171',
  },
  toastMessageRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toastIcon: {
    fontSize: 16,
  },
  toastMessage: {
    flex: 1,
    fontSize: 13,
    color: '#0f172a',
  },
  toastActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#0f172a',
    backgroundColor: '#ffffff',
  },
  toastActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0f172a',
  },
  placeholderCard: {
    padding: 24,
    borderRadius: 20,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 8,
  },
  placeholderTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
  },
  placeholderText: {
    fontSize: 14,
    color: '#6b7280',
    lineHeight: 20,
  },
  taskListContainer: {
    gap: 16,
  },
  loadingCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 13,
    color: '#6b7280',
  },
  errorCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fca5a5',
  },
  errorText: {
    fontSize: 13,
    color: '#b91c1c',
  },
  authSafeArea: {
    flex: 1,
    backgroundColor: WORK_LIGHT,
  },
  authScreen: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 32,
    backgroundColor: WORK_LIGHT,
  },
  authShell: {
    flex: 1,
    gap: 32,
    justifyContent: 'space-between',
  },
  authHeroSection: {
    borderRadius: 28,
    paddingVertical: 48,
    paddingHorizontal: 24,
    backgroundColor: WORK_DARK,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexShrink: 0,
  },
  authHeroBadge: {
    fontSize: 48,
    fontWeight: '800',
    letterSpacing: 8,
    color: '#f8fafc',
    textTransform: 'uppercase',
  },
  authHeroHint: {
    fontSize: 13,
    color: '#d3e0ff',
  },
  authFormSection: {
    borderRadius: 28,
    backgroundColor: WORK_LIGHT,
    padding: 4,
  },
  authFormCard: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    padding: 24,
    gap: 16,
    minHeight: 420,
    ...createShadowStyle({ color: WORK_DARK, opacity: 0.08, offsetX: 0, offsetY: 16, radius: 24 }),
    elevation: 8,
  },
  authFormCardBody: {
    flex: 1,
    paddingTop: 12,
  },
  authFormSections: {
    flex: 1,
    justifyContent: 'space-between',
    gap: 20,
  },
  authFieldsBlock: {
    gap: 16,
    minHeight: 220,
  },
  authActionsBlock: {
    gap: 12,
  },
  authForgotSpacer: {
    height: 48,
  },
  authPanelStack: {
    flex: 1,
    justifyContent: 'space-between',
  },
  authFormStack: {
    gap: 16,
  },
  authFormHeader: {
    gap: 4,
  },
  authFormTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: WORK_MID,
  },
  authFormSubtitle: {
    fontSize: 13,
    color: WORK_ACCENT,
  },
  authFieldSpacer: {
    height: 74,
  },
  authDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: WORK_ACCENT_SOFT,
  },
  authDividerLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: WORK_ACCENT,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  authSocialSection: {
    gap: 12,
  },
  authSocialWrapper: {
    borderRadius: 28,
    backgroundColor: '#ffffff',
    padding: 20,
    ...createShadowStyle({ color: WORK_DARK, opacity: 0.06, offsetX: 0, offsetY: 10, radius: 20 }),
    elevation: 6,
    gap: 16,
  },
  authSocialHeading: {
    fontSize: 15,
    fontWeight: '600',
    color: WORK_MID,
  },
  authSocialIconRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  authSocialIconButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: WORK_ACCENT_SOFT,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authSocialIconOnly: {
    color: WORK_MID,
  },
  authSocialHint: {
    fontSize: 12,
    color: WORK_ACCENT,
  },
  homeScreen: {
    gap: 16,
    paddingBottom: 96,
    position: 'relative',
  },
  homeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    ...createShadowStyle({ color: WORK_DARK, opacity: 0.06, offsetX: 0, offsetY: 10, radius: 18 }),
    elevation: 5,
    marginBottom: 20,
  },
  homeHeaderText: {
    flex: 1,
    gap: 12,
  },
  homeGreeting: {
    fontSize: 22,
    fontWeight: '700',
    color: WORK_MID,
  },
  homeGreetingSubtitle: {
    fontSize: 13,
    color: '#64748b',
  },
  homeAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: WORK_MID,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
  },
  homeHeaderActionButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  homeOrgHint: {
    fontSize: 13,
    color: '#94a3b8',
  },
  homeSummaryCard: {
    flexBasis: '48%',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 14,
    minHeight: 64,
    justifyContent: 'space-between',
  },
  homeSummaryRow: {
    gap: 10,
  },
  homeSummaryTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
  },
  homeSummaryLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 1,
  },
  homeSummaryIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeSummaryLabel: {
    fontSize: 13,
    color: '#1f2937',
  },
  homeSummaryValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
    textAlign: 'center',
    width: '100%',
  },
  homeSummaryValueCaption: {
    fontSize: 12,
    color: '#475569',
    textAlign: 'center',
  },
  homeQuickMenuOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
    elevation: 10,
  },
  homeQuickMenuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  homeQuickMenuContainer: {
    flex: 1,
    alignItems: 'flex-end',
    paddingTop: 68,
    paddingRight: 12,
  },
  homeQuickMenu: {
    width: 200,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    gap: 4,
    ...createShadowStyle({ color: '#000000', opacity: 0.16, offsetX: 0, offsetY: 8, radius: 20 }),
  },
  homeQuickMenuArrow: {
    width: 16,
    height: 16,
    backgroundColor: '#ffffff',
    alignSelf: 'flex-end',
    marginRight: 24,
    marginBottom: -8,
    transform: [{ rotate: '45deg' }],
  },
  homeQuickMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  homeQuickMenuIcon: {
    width: 20,
    textAlign: 'center',
  },
  homeQuickMenuLabel: {
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '500',
  },
  homeTaskList: {
    gap: 12,
  },
  homeTaskCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e0e7ff',
    backgroundColor: '#f8fbff',
    padding: 16,
    gap: 6,
  },
  homeTaskMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  homeTaskMetaText: {
    fontSize: 12,
    color: '#475569',
  },
  homeTaskStatus: {
    fontSize: 12,
    fontWeight: '600',
    color: WORK_MID,
  },
  homeTaskTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
  },
  homeTaskDescription: {
    fontSize: 13,
    color: '#475569',
  },
  homeEmptyTasks: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    paddingVertical: 24,
  },
  homeSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
    marginTop: 12,
    marginBottom: 8,
  },
  accountScreen: {
    gap: 20,
  },
  profileCard: {
    borderRadius: 28,
    backgroundColor: '#fdf2f8',
    padding: 20,
    gap: 12,
    ...createShadowStyle({ color: '#f472b6', opacity: 0.2, offsetX: 0, offsetY: 8, radius: 20 }),
  },
  accountSection: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    padding: 16,
    gap: 12,
    ...createShadowStyle({ color: '#000000', opacity: 0.04, offsetX: 0, offsetY: 6, radius: 16 }),
  },
  accountSectionLavender: {
    backgroundColor: '#f4f0ff',
  },
  accountSectionMint: {
    backgroundColor: '#ecfdf5',
  },
  accountSectionSand: {
    backgroundColor: '#fff7ed',
  },
  accountSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  accountSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  accountSectionBody: {
    marginTop: 12,
    gap: 16,
  },
  accountHeader: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
  },
  profilePlanBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  profilePlanBadge: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#fee2e2',
  },
  profilePlanBadgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#b91c1c',
  },
  profilePlanDetail: {
    fontSize: 12,
    color: '#9f1239',
    flexShrink: 1,
  },
  accountAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: WORK_LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: WORK_ACCENT_SOFT,
  },
  accountAvatarInitial: {
    fontSize: 28,
    fontWeight: '700',
    color: WORK_MID,
  },
  accountHeaderText: {
    flex: 1,
    gap: 4,
  },
  accountNameEditRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  accountNameInput: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    color: '#111827',
  },
  accountSaveButton: {
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: WORK_MID,
  },
  accountSaveButtonText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  accountName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  accountNameHint: {
    fontSize: 12,
    color: '#94a3b8',
  },
  accountNameLimit: {
    fontSize: 12,
    color: '#a21caf',
  },
  accountJoined: {
    fontSize: 13,
    color: '#6b7280',
  },
  accountMenu: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    ...createShadowStyle({ color: WORK_DARK, opacity: 0.04, offsetX: 0, offsetY: 8, radius: 18 }),
    elevation: 4,
  },
  accountMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  accountMenuIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: WORK_LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  accountMenuLabel: {
    flex: 1,
    fontSize: 15,
    color: '#1f2937',
  },
  accountMenuChevron: {
    fontSize: 20,
    color: '#cbd5f5',
  },
  accountOrgCard: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    padding: 20,
    gap: 12,
    ...createShadowStyle({ color: WORK_DARK, opacity: 0.04, offsetX: 0, offsetY: 8, radius: 18 }),
  },
  accountOrgCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
  },
  accountOrgCardMeta: {
    fontSize: 13,
    color: '#6b7280',
  },
  orgHubCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orgHubCardActions: {
    flexDirection: 'row',
    gap: 8,
  },
  accountOrgRow: {
    borderRadius: 20,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...createShadowStyle({ color: WORK_DARK, opacity: 0.04, offsetX: 0, offsetY: 8, radius: 18 }),
  },
  accountOrgRowPublic: {
    backgroundColor: '#fef2f2',
  },
  accountOrgRowPrivate: {
    backgroundColor: '#ecfdf5',
  },
  accountOrgRowName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    flex: 1,
    marginRight: 12,
  },
  accountOrgRowMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  orgHubRowLeft: {
    flex: 1,
    marginRight: 12,
  },
  accountOrgRowBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  accountOrgRowBadgePublic: {
    backgroundColor: '#fee2e2',
  },
  accountOrgRowBadgePrivate: {
    backgroundColor: '#bbf7d0',
  },
  accountOrgRowBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0f172a',
  },
  accountOrgHint: {
    fontSize: 12,
    color: '#94a3b8',
  },
  orgRowAction: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountOrgBadgeRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
    marginBottom: 4,
  },
  accountOrgBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#e0f2fe',
  },
  accountOrgBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0369a1',
  },
  visibilityToggle: {
    gap: 6,
  },
  accountOrgEmptyCard: {
    borderRadius: 20,
    backgroundColor: '#ffffff',
    padding: 20,
    gap: 10,
    ...createShadowStyle({ color: '#94a3b8', opacity: 0.1, offsetX: 0, offsetY: 6, radius: 16 }),
  },
  accountOrgEmptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
  },
  accountOrgEmptyText: {
    fontSize: 13,
    color: '#6b7280',
  },
  accountInlineField: {
    marginTop: 12,
    gap: 10,
  },
  accountList: {
    marginTop: 20,
    gap: 10,
  },
  accountListTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  accountListEmpty: {
    fontSize: 13,
    color: '#94a3b8',
  },
  accountListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 12,
  },
  accountListItemText: {
    flex: 1,
    gap: 4,
  },
  accountListPrimary: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0f172a',
  },
  accountListSecondary: {
    fontSize: 12,
    color: '#6b7280',
  },
  accountListTag: {
    fontSize: 12,
    fontWeight: '600',
    color: '#15803d',
  },
  joinActionRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  joinActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 16,
    borderRadius: 18,
    backgroundColor: '#ecfdf5',
    flexGrow: 1,
    flexBasis: 0,
  },
  joinActionButtonSecondary: {
    backgroundColor: '#e0f2fe',
  },
  joinActionButtonDisabled: {
    opacity: 0.45,
  },
  joinActionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinActionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  joinActionHint: {
    fontSize: 12,
    color: '#475569',
  },
  joinHistoryCard: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: '#f8fafc',
    gap: 12,
  },
  joinHistoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  joinHistoryTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
  },
  joinHistoryRefresh: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  joinHistoryRefreshText: {
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '600',
  },
  joinHistoryEmpty: {
    alignItems: 'center',
    gap: 6,
  },
  joinHistoryEmptyText: {
    fontSize: 13,
    color: '#6b7280',
  },
  joinHistoryItem: {
    borderRadius: 16,
    padding: 14,
    backgroundColor: '#ffffff',
    gap: 4,
  },
  joinHistoryInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  joinHistoryOrg: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  joinHistoryStatus: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0f172a',
  },
  joinHistoryStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  joinHistoryDelete: {
    marginLeft: 8,
    padding: 4,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
  },
  joinHistoryMeta: {
    fontSize: 12,
    color: '#475569',
  },
  joinHistoryNote: {
    fontSize: 13,
    color: '#0f172a',
  },
  joinManageSheet: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: '#f8fafc',
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 24,
    maxHeight: '90%',
    gap: 12,
  },
  joinManageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  joinManageHeaderText: {
    flex: 1,
  },
  joinManageTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#0f172a',
  },
  joinManageSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#475569',
  },
  joinManageRefresh: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  joinManageRefreshText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0f172a',
  },
  joinManageList: {
    gap: 12,
  },
  joinManageItem: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#ffffff',
    gap: 12,
  },
  joinManageInfo: {
    gap: 4,
  },
  joinManageName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  joinManageMeta: {
    fontSize: 12,
    color: '#475569',
  },
  joinManageMessage: {
    fontSize: 13,
    color: '#0f172a',
  },
  joinManageActions: {
    flexDirection: 'row',
    gap: 10,
  },
  joinManageApprove: {
    flex: 1,
    borderColor: '#16a34a',
  },
  joinManageReject: {
    flex: 1,
    borderColor: '#dc2626',
  },
  orgHubJoinCard: {
    marginTop: 20,
    borderRadius: 24,
    backgroundColor: '#eef2ff',
    padding: 20,
    gap: 16,
  },
  orgHubJoinTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  orgHubJoinSubtitle: {
    fontSize: 13,
    color: '#475569',
  },
  orgHubDivider: {
    height: 1,
    backgroundColor: '#dbeafe',
    marginVertical: 4,
  },
  orgHubJoinButton: {
    marginTop: 20,
    borderRadius: 24,
    backgroundColor: '#0ea5e9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    gap: 16,
  },
  orgHubJoinButtonText: {
    flex: 1,
    color: '#ecfeff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  orgHubJoinIcon: {
    width: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  membershipLoading: {
    marginTop: 20,
  },
  membershipSection: {
    marginTop: 24,
    gap: 12,
  },
  membershipSectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0f172a',
  },
  membershipSectionHint: {
    fontSize: 13,
    color: '#475569',
  },
  membershipList: {
    gap: 12,
  },
  membershipCard: {
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  membershipCardOwner: {
    backgroundColor: '#dcfce7',
  },
  membershipCardAdmin: {
    backgroundColor: '#dbeafe',
  },
  membershipCardMember: {
    backgroundColor: '#f8fafc',
  },
  membershipInfo: {
    flex: 1,
    gap: 4,
  },
  membershipName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  membershipRole: {
    fontSize: 13,
    color: '#0c4a6e',
  },
  membershipDisplayName: {
    fontSize: 12,
    color: '#0f172a',
  },
  membershipActions: {
    flexDirection: 'row',
    gap: 8,
  },
  membershipActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinPage: {
    flex: 1,
    backgroundColor: '#0ea5e9',
  },
  joinPageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    gap: 12,
  },
  joinPageBack: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinPageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
  },
  joinPageSubtitle: {
    fontSize: 13,
    color: '#475569',
  },
  joinPageLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  joinPageLinkText: {
    color: '#0f172a',
    fontWeight: '600',
  },
  joinPageContent: {
    padding: 20,
    gap: 20,
    paddingBottom: 80,
  },
  joinPageSection: {
    borderRadius: 24,
    backgroundColor: '#f0f9ff',
    padding: 16,
    gap: 12,
  },
  joinPageSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  joinPageSectionHint: {
    fontSize: 13,
    color: '#475569',
  },
  joinPageSectionSubtitle: {
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '600',
  },
  joinPageMeta: {
    fontSize: 12,
    color: '#0c4a6e',
  },
  joinSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  joinResultList: {
    gap: 12,
  },
  joinResultCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#dbeafe',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  joinResultCardActive: {
    borderColor: '#0ea5e9',
    backgroundColor: '#f0f9ff',
  },
  joinInfoCard: {
    borderRadius: 16,
    backgroundColor: '#eef2ff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
  },
  joinInfoText: {
    fontSize: 13,
    color: '#0f172a',
  },
  joinResultName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  joinResultDescription: {
    fontSize: 13,
    color: '#475569',
  },
  accountOrgShortcut: {
    marginTop: 12,
    borderRadius: 18,
    backgroundColor: '#ecfdf5',
    paddingVertical: 14,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  accountOrgShortcutText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  contactsScreen: {
    gap: 16,
  },
  contactsList: {
    gap: 12,
  },
  contactCard: {
    borderRadius: 20,
    padding: 18,
    backgroundColor: '#ffffff',
    gap: 6,
  },
  contactName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  contactRole: {
    fontSize: 13,
    color: '#475569',
  },
  contactTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  contactTagChip: {
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  contactTagText: {
    fontSize: 12,
    color: '#0f172a',
  },
  contactsEmpty: {
    fontSize: 14,
    color: '#475569',
    textAlign: 'center',
    marginTop: 12,
  },
  tagFilterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  tagFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#e0f2fe',
  },
  tagFilterButtonIcon: {
    color: '#0f172a',
  },
  tagFilterButtonLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  tagFilterButtonBadge: {
    fontSize: 12,
    color: '#0369a1',
  },
  tagFilterClear: {
    fontSize: 13,
    color: '#0ea5e9',
    fontWeight: '600',
  },
  tagFilterSheet: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: '#f8fafc',
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 24,
    maxHeight: '90%',
    gap: 16,
  },
  tagFilterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  tagFilterHeaderText: {
    flex: 1,
  },
  tagFilterTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#0f172a',
  },
  tagFilterSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#475569',
  },
  tagFilterContent: {
    gap: 16,
    paddingBottom: 12,
  },
  tagFilterCategory: {
    gap: 8,
  },
  tagFilterCategoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  tagFilterCategoryTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  tagFilterCategoryMeta: {
    fontSize: 12,
    color: '#64748b',
  },
  tagFilterChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tagFilterChip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#cbd5f5',
    backgroundColor: '#ffffff',
  },
  tagFilterChipActive: {
    borderColor: '#0ea5e9',
    backgroundColor: '#e0f2fe',
  },
  tagFilterChipLabel: {
    fontSize: 13,
    color: '#1e293b',
    fontWeight: '500',
  },
  tagFilterChipLabelActive: {
    fontSize: 13,
    color: '#075985',
    fontWeight: '600',
  },
  tagFilterEmpty: {
    fontSize: 12,
    color: '#94a3b8',
  },
  tagFilterFooter: {
    flexDirection: 'row',
    gap: 12,
  },
  accountInput: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: '#111827',
  },
  accountOrgSlug: {
    fontSize: 12,
    color: '#94a3b8',
  },
  orgTile: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 24,
    backgroundColor: '#e0f2fe',
    ...createShadowStyle({ color: '#0ea5e9', opacity: 0.2, offsetX: 0, offsetY: 6, radius: 18 }),
  },
  orgTileTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
  },
  orgTileSubtitle: {
    fontSize: 13,
    color: '#0c4a6e',
    marginTop: 4,
  },
  orgTileIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  orgTileIconRow: {
    flexDirection: 'row',
    gap: 8,
  },
  orgTileBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  orgTileBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  signOutButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#fca5a5',
    paddingVertical: 14,
    alignItems: 'center',
  },
  signOutButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#b91c1c',
  },
  toggleRow: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 999,
    backgroundColor: '#f4f4f5',
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: 'center',
  },
  toggleButtonActive: {
    backgroundColor: '#ffffff',
    ...createShadowStyle({ color: '#000000', opacity: 0.08, offsetX: 0, offsetY: 4, radius: 16 }),
    elevation: 4,
  },
  toggleLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6b7280',
  },
  toggleLabelActive: {
    color: '#111827',
  },
  fieldGroup: {
    gap: 6,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  input: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#111827',
    backgroundColor: '#ffffff',
  },
  primaryButton: {
    height: 48,
    borderRadius: 12,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 18,
    marginTop: 12,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  publishModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'flex-end',
  },
  publishModalCard: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 16,
    maxHeight: '90%',
    ...createShadowStyle({ color: '#000000', opacity: 0.2, offsetX: 0, offsetY: -4, radius: 20 }),
  },
  publishModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  publishModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  publishModalClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  planModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.55)',
    justifyContent: 'center',
    padding: 24,
  },
  planModalCard: {
    borderRadius: 28,
    backgroundColor: '#ffffff',
    padding: 20,
    gap: 16,
    ...createShadowStyle({ color: '#000000', opacity: 0.2, offsetX: 0, offsetY: 6, radius: 24 }),
  },
  planModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  planModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  planModalClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  planModalDetail: {
    fontSize: 13,
    color: '#475569',
  },
  planLimitList: {
    gap: 8,
  },
  planLimitItem: {
    fontSize: 14,
    color: '#0f172a',
  },
  planUpgradeButton: {
    marginTop: 4,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  planUpgradeButtonText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  secondaryButton: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 12,
  },
  secondaryButtonText: {
    color: '#374151',
    fontSize: 15,
    fontWeight: '500',
  },
  buttonPressed: {
    opacity: 0.9,
  },
  buttonPressedLight: {
    backgroundColor: '#f9fafb',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  orgHubSafeArea: {
    flex: 1,
    backgroundColor: '#e0f2fe',
  },
  orgHubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  orgHubBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orgHubTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  orgHubHeaderSpacer: {
    width: 40,
  },
  orgHubBody: {
    flex: 1,
    padding: 20,
    gap: 16,
  },
  orgHubSubtitle: {
    fontSize: 13,
    color: '#475569',
  },
  orgHubList: {
    gap: 12,
  },
  orgHubListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    ...createShadowStyle({ color: '#0f172a', opacity: 0.08, offsetX: 0, offsetY: 8, radius: 18 }),
  },
  orgHubListInfo: {
    flex: 1,
    gap: 4,
  },
  orgHubOrgName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
  },
  orgHubOrgMeta: {
    fontSize: 13,
    color: '#64748b',
  },
  orgHubActions: {
    flexDirection: 'row',
    gap: 8,
  },
  orgHubActionIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orgHubActionDisabled: {
    opacity: 0.4,
  },
  orgHubEmpty: {
    padding: 20,
    borderRadius: 20,
    backgroundColor: '#eef2ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orgHubEmptyText: {
    fontSize: 14,
    color: '#475569',
    textAlign: 'center',
  },
  orgHubOrgDescription: {
    fontSize: 13,
    color: '#475569',
  },
  orgHubVisibilityBadge: {
    marginTop: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#e0f2fe',
  },
  orgHubVisibilityBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0369a1',
  },
  orgHubCreateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 16,
    paddingVertical: 12,
    backgroundColor: '#2563eb',
  },
  orgHubCreateButtonText: {
    color: '#ecfdf5',
    fontWeight: '600',
  },
  orgHubHint: {
    fontSize: 12,
    color: '#475569',
    textAlign: 'center',
  },
  orgCreateOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.45)',
    justifyContent: 'flex-end',
  },
  orgCreateSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#ffffff',
    padding: 20,
    gap: 12,
  },
  orgCreateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orgCreateTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  orgCreateClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orgImmutableHint: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 18,
    lineHeight: 16,
  },
  orgSettingsSheet: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: '#f8fafc',
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 16,
    maxHeight: '90%',
  },
  orgSettingsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  orgSettingsHeaderText: {
    flex: 1,
    paddingRight: 12,
  },
  orgSettingsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
  },
  orgSettingsSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#475569',
    lineHeight: 18,
  },
  orgSettingsClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
  },
  orgSettingsScroll: {
    flexGrow: 0,
  },
  orgSettingsScrollContent: {
    paddingBottom: 24,
    gap: 16,
  },
  orgSettingsCard: {
    borderRadius: 24,
    padding: 20,
    gap: 12,
  },
  orgSettingsCardSky: {
    backgroundColor: '#e0f2fe',
  },
  orgSettingsCardMint: {
    backgroundColor: '#dcfce7',
  },
  orgSettingsCardPeach: {
    backgroundColor: '#fef3c7',
  },
  orgSettingsCardNeutral: {
    backgroundColor: '#f1f5f9',
  },
  orgSettingsCardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0f172a',
  },
  orgSettingsBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  orgSettingsBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  orgSettingsBadgePublic: {
    backgroundColor: '#fee2e2',
  },
  orgSettingsBadgePrivate: {
    backgroundColor: '#bbf7d0',
  },
  orgSettingsBadgeNeutral: {
    backgroundColor: '#e2e8f0',
  },
  orgSettingsBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0f172a',
  },
  orgSettingsPlanLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  orgSettingsPlanDetail: {
    fontSize: 13,
    color: '#334155',
  },
  orgSettingsStatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  orgSettingsStatLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0f172a',
  },
  orgSettingsDescription: {
    fontSize: 13,
    color: '#475569',
    lineHeight: 18,
  },
  orgSettingsBody: {
    fontSize: 13,
    color: '#1f2937',
    lineHeight: 18,
  },
  orgSettingsDefaultCount: {
    fontSize: 14,
    fontWeight: '600',
    color: '#065f46',
  },
  orgSettingsActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  orgSettingsFootnote: {
    fontSize: 12,
    color: '#475569',
  },
  orgSettingsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orgSettingsUsage: {
    fontSize: 12,
    color: '#0f172a',
    fontWeight: '600',
  },
  orgGroupList: {
    gap: 10,
  },
  orgGroupRow: {
    borderRadius: 18,
    padding: 12,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orgGroupInfo: {
    flex: 1,
    marginRight: 12,
    gap: 2,
  },
  orgGroupName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  orgGroupMeta: {
    fontSize: 12,
    color: '#475569',
  },
  orgGroupAction: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
  },
  orgSettingsFooter: {
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orgSettingsFooterHint: {
    fontSize: 12,
    color: '#64748b',
    flex: 1,
  },
  orgSettingsFooterLink: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0ea5e9',
    marginLeft: 12,
  },
  sessionBlock: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
  },
  sessionLabel: {
    fontSize: 12,
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  sessionEmail: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
  },
  sessionAid: {
    marginTop: 2,
    fontSize: 12,
    color: '#6b7280',
  },
  sessionActions: {
    flexDirection: 'row',
    gap: 12,
  },

  tabRow: {
    flexDirection: 'row',
    gap: 8,
  },
  tabButton: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#f4f4f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#111827',
  },
  tabLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
  },
  tabLabelActive: {
    color: '#ffffff',
  },
  section: {
    gap: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
  },
  sectionHint: {
    fontSize: 13,
    color: '#6b7280',
  },
  chipRow: {
    flexDirection: 'row',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#f4f4f5',
  },
  chipActive: {
    backgroundColor: '#111827',
  },
  chipLabel: {
    fontSize: 13,
    color: '#6b7280',
  },
  chipLabelActive: {
    color: '#ffffff',
  },
  formField: {
    gap: 8,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  textInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#111827',
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  helperText: {
    fontSize: 12,
    color: '#6b7280',
  },
  publishTemplateCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
    padding: 16,
    gap: 8,
  },
  publishTemplateTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
  },
  publishTemplateDescription: {
    fontSize: 13,
    color: '#4b5563',
    lineHeight: 18,
  },
  publishTemplateChecklist: {
    marginTop: 8,
    gap: 6,
  },
  publishTemplateChecklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  publishTemplateChecklistIcon: {
    fontSize: 14,
  },
  publishTemplateChecklistLabel: {
    fontSize: 13,
    color: '#1f2937',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  loadingBox: {
    alignItems: 'center',
    gap: 8,
  },
  successText: {
    fontSize: 13,
    color: '#047857',
  },
  emptyText: {
    fontSize: 13,
    color: '#6b7280',
  },
  insightRow: {
    flexDirection: 'row',
    gap: 12,
  },
  insightCard: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
    padding: 16,
    gap: 8,
  },
  insightLabel: {
    fontSize: 12,
    color: '#6b7280',
    textTransform: 'uppercase',
  },
  insightValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  insightList: {
    marginTop: 16,
    gap: 12,
  },
  insightListItem: {
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    gap: 4,
  },
  insightListTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
  },
  insightListMeta: {
    fontSize: 12,
    color: '#6b7280',
  },
  insightTrendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  insightTrendLabelCol: {
    flex: 1,
    gap: 2,
  },
  insightTrendBarTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#e5e7eb',
    flexDirection: 'row',
    overflow: 'hidden',
    minWidth: 120,
  },
  insightTrendBarFill: {
    height: '100%',
  },
  timeline: {
    gap: 12,
  },
  timelineList: {
    gap: 12,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineIconWrapper: {
    alignItems: 'center',
  },
  timelineIcon: {
    fontSize: 18,
  },
  timelineConnector: {
    width: 2,
    flex: 1,
    backgroundColor: '#e5e7eb',
    marginTop: 4,
  },
  timelineContent: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    padding: 12,
    gap: 4,
  },
  timelineLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  timelineMeta: {
    fontSize: 12,
    color: '#6b7280',
  },
  checklist: {
    gap: 8,
  },
  checklistHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
  },
  checklistItemChecked: {
    opacity: 0.6,
  },
  checklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checklistIcon: {
    fontSize: 18,
  },
  checklistLabel: {
    fontSize: 14,
    color: '#111827',
  },
  checklistLabelChecked: {
    textDecorationLine: 'line-through',
    color: '#6b7280',
  },
  checklistInputRow: {
    gap: 8,
  },
  chipDanger: {
    borderColor: '#fecaca',
    backgroundColor: '#fee2e2',
  },
  chipDangerText: {
    fontSize: 12,
    color: '#b91c1c',
    fontWeight: '600',
  },
} as const satisfies NamedStyles;
